title: ""
name: "Dzenyu Mukangara"
description: >-
  Principal Software Engineer sharing architecture insights, coding practices,
  and engineering leadership lessons.
url: "https://code.dzenyu.com"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.26.2"

# Theme skin and locale
# minimal_mistakes_skin controls the color scheme for the Minimal Mistakes theme.
# Available skins you can try:
#   default, air, aqua, contrast, dark, dirt, neon, mint, plum, sunrise
# To test: change the value below, then `bundle exec jekyll serve` and refresh.
minimal_mistakes_skin: "sunrise"
locale: "en-US"

# GitHub Pages–compatible plugins
plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Site features
search: true

# Author profile
author:
  name   : "Dzenyu Mukangara"
#  avatar : "/assets/images/avatar.jpg"
  avatar : "/assets/images/my-avatar.png"
  bio    : "Principal Engineer, Engineering Leadership | Java, Spring, Kafka, AWS | Mentoring, Coaching, Micro Services"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/dzenyu"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/smukangara"

# Comments provider (Utterances)
comments:
  provider: "utterances"
  utterances:
    repo: "dzenyu/dzenyu.github.io"
    issue_term: "pathname"
    label: "💬 comment"
    theme: "github-light"

# Front matter defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      comments: false
      show_date: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      comments: false
