title: ""
name: "Dzenyu Mukangara"
description: "Engineering leadership, architecture, and system design insights"
url: "https://code.dzenyu.com"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"

minimal_mistakes_skin: "contrast"
locale: "en-US"

# Enable site-wide Mermaid toggle so layouts/includes can conditionally load the script
mermaid: false

enable_copy_code_button: true

breadcrumbs: false  # disabled by default

# Markdown + syntax highlighting
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# GitHub Pages–compatible plugins
plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives
  # NOTE: If you want advanced pagination (v2), you'll need to build with GitHub Actions and add:
  # - jekyll-paginate-v2

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Site features
search: true

# Author profile
author:
  name   : "Dzenyu Mukangara"
  avatar : "/assets/images/my-avatar.png"
  bio    : "Principal Engineer, Engineering Leadership, Micro Services, Cloud (AWS), Mentoring, AI"
  location : "DFW, USA"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/dzenyu"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/smukangara"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://x.com/dzenyu"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/dzenyu"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/smukangara"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://x.com/dzenyu"

# Comments provider (disqus)
repository: "dzenyu/dzenyu.github.io"
comments:
  provider: "disqus"
  disqus:
    shortname: "dzenyu"

# Front matter defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
      comments: true
      layout: single
      read_time: true
      related: true
      share: true
      show_date: true
      toc: true
      toc_sticky: true
      # Optionally let posts opt-out of Mermaid by setting mermaid: false in a post
      mermaid: false
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      comments: false
      share: true

seo:
  type: "Blog"
  name: "Dzenyu Mukangara"

# Pagination:
# These options are for jekyll-paginate-v2. If you are using GitHub Pages' native build,
# either migrate to GitHub Actions and enable the plugin, or remove this block for now.
pagination:
  enabled: true
  collection: 'posts'
  per_page: 5
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2

# Optional: pretty permalinks
#permalink: /:categories/:year/:month/:day/:title/

compress_html:
  clippings: all
#  ignore:
#    envs: development

# Analytics: G-QNVTKW04G1
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-QNVTKW04G1"
    anonymize_ip: false # true/false
