title: ""
name: "Dzenyu Mukangara"
description: >-
  Principal Software Engineer sharing architecture insights, coding practices,
  and engineering leadership lessons.
url: "https://code.dzenyu.com"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.26.2"

# Theme skin and locale
# minimal_mistakes_skin controls the color scheme for the Minimal Mistakes theme.
# Available skins you can try:
#   default, air, aqua, contrast, dark, dirt, neon, mint, plum, sunrise
# To test: change the value below, then `bundle exec jekyll serve` and refresh.
minimal_mistakes_skin: "contrast"
locale: "en-US"

enable_copy_code_button: true

# GitHub Pages–compatible plugins
plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Site features
search: true

# Author profile
author:
  name   : "Dzenyu Mukangara"
#  avatar : "/assets/images/avatar.jpg"
  avatar : "/assets/images/my-avatar.png"
  bio    : "Principal Engineer, Engineering Leadership | Mentoring, Coaching, Micro Services, Cloud Computing, AI"
  location : "Dallas, USA"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/dzenyu"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/smukangara"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://x.com/dzenyu"

# Comments provider (disqus)
repository: "dzenyu/dzenyu.github.io"
comments:
  provider: "disqus"
  disqus:
    shortname: "dzenyu"  # <-- replace with your Disqus shortname

# Front matter defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
      comments: true
      layout: single
      read_time: true
      related: true
      share: true
      show_date: true
      toc: true
      toc_sticky: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      comments: false

seo:
  type: "Blog"
  name: "Dzenyu Mukangara"

pagination:
  enabled: true
  collection: 'posts'
  per_page: 5
  permalink: '/page/:num/'  # Pages are index.html inside this folder (default)
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2

compress_html:
  clippings: all
#  ignore:
#    envs: development  # disable compression in dev environment

# Analytics: G-QNVTKW04G1
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-QNVTKW04G1"
    anonymize_ip: false # true/false

